import '../api/test';
import '../api/linio';
import '../api/falabella';
import '../api/exito';
import '../api/mercadoLibre';
import '../api/buscador';
import '../api/elementosVistos';
import '../api/palabrasBuscadas';
import '../api/recomendadosIniciales';
